[package]
name = "meet-copilot-platform-macos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
block2 = { workspace = true }
dispatch2 = { workspace = true }
meet-copilot-core = { workspace = true }
objc2 = { workspace = true }
objc2-core-audio-types = { workspace = true }
objc2-core-foundation = { workspace = true }
objc2-core-graphics = { workspace = true }
objc2-core-media = { workspace = true }
objc2-foundation = { workspace = true }
objc2-screen-capture-kit = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
